### ISSUE TITLE
Is there any ready-to-use function for minimising all nodes when loading the window?

### ISSUE THREAD

**Issue by jonatask** [NexZhu/SkillSet#4]

**Comment by NexZhu** [comment]
If you mean collapsing all nodes, the KityMinder library does have an API for that:
`minder.execCommand('ExpandToLevel', level);`

**Comment by jonatask** [comment]
This works, but some seconds later the page renders and system shows it expanded again.
The exact behaviour I would like is:
- All nodes collapsed when loading the page.
- When I click a node, it expands just 1 more level.

Do you know where I could replace code for seeing this behaviour?

Thanks.

**Comment by jonatask** [comment]
Thank you.
